name: Build n Deploy

on:
    - push
    - workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 10.10.0
                  run_install: false

            - uses: actions/setup-node@v4
              with:
                  node-version: 22.15.0
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Lint
              run: pnpm run lint
